font_family JetBrainsMono Nerd Font
bold_font JetBrainsMono Nerd Font Bold
italic_font JetBrainsMono Nerd Font Italic
bold_italic_font JetBrainsMono Nerd Font Bold Italic
font_size 12.0
disable_ligatures cursor
strip_trailing_spaces smart

cursor_shape block
cursor_blink_interval 0.5
cursor_trail 3

scrollback_lines 10000
scrollback_pager_history_size 50

window_padding_width 4

tab_bar_edge bottom
tab_bar_style powerline
tab_powerline_style slanted
tab_title_template "{index}: {title}"
tab_bar_min_tabs 1

enable_audio_bell no
notify_on_cmd_finish unfocused 10

map ctrl+shift+t new_tab_with_cwd
map ctrl+shift+enter new_window_with_cwd
map ctrl+1 goto_tab 1
map ctrl+2 goto_tab 2
map ctrl+3 goto_tab 3
map ctrl+4 goto_tab 4
map ctrl+5 goto_tab 5


include current-theme.conf
